# Nom de l'application
spring.application.name=MA-VILLE

# ===============================
# CONFIGURATION POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ma_ville
spring.datasource.username=postgres
spring.datasource.password=TON_MOT_DE_PASSE
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVEUR
# ===============================
server.port=8080